 
services:
  leafletalarmsservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8000;http://+:${GRPC_MAIN_PORT}
      - Kestrel__Endpoints__gRPC__Url=http://*:${GRPC_MAIN_PORT}
      - Kestrel__Endpoints__gRPC__Protocols=Http2
      - Kestrel__Endpoints__Http__Url=http://*:8000
      #- REACT_APP_AUTH_SERVER_URL=http://localhost1:8080/
    ports:
      - "8000:8000"
      - ${GRPC_MAIN_PORT}:${GRPC_MAIN_PORT}
    image: pruginkad/leafletalarms:latest
    restart: unless-stopped
    depends_on:
     - mongoservice
     - keycloakservice
     - redisservice
    volumes:
      - ./leaflet_data:/leaflet_data
    env_file:
      - global.env
      - .env


  grpctracksclient:
    image: pruginkad/grpctracksclient:latest
    build:
      context: .
      dockerfile: GrpcTracksClient/Dockerfile
    env_file:
      - global.env
      - .env
    environment:
      - VALHALLA_PORT:${VALHALLA_PORT}
    depends_on:
      - valhallaservice
      - leafletalarmsservice
 
  blinkservice:
    image: pruginkad/blinkservice:latest
    build:
      context: .
      dockerfile: BlinkService/Dockerfile
    env_file:
      - global.env

  mongoservice:
    image : mongo
    container_name: mongodb
    restart: unless-stopped
    volumes: 
      #- ./mongo_data/:/data/db #this option put all into yml folder
     - ./leaflet_data/mongo_data/:/data/db
    ports:
     - "27017:27017"
     #- "27018:27017"

  redisservice:
    image: redis
    restart: unless-stopped
    environment:
     - ALLOW_EMPTY_PASSWORD=yes
    ports:
     - "6379:6379"

# START keycloack
  postgresservice:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./leaflet_data/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  keycloakservice:
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    volumes:
      - ./keycloak_imports:/opt/keycloak/data/import
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresservice:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KEYCLOAK_LOGLEVEL: ALL
      ROOT_LOGLEVEL: ALL
    command: 
      - start-dev
      - --import-realm
    ports:
      - 8080:8080
    depends_on:
      - postgresservice
# command2export realm:docker exec -ti leaflet-keycloakservice-1 /opt/keycloak/bin/kc.sh export --file /opt/keycloak/data/import/realm-export1.json --realm myrealm
# END keycloak

  valhallaservice:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    restart: unless-stopped
    container_name: valhalla_latest
    ports:
      - ${VALHALLA_PORT}:${VALHALLA_PORT}
    volumes:
      - ./leaflet_data/valhalla_custom_files/:/custom_files
